baseURL = 'https://Arian-D.github.io/ctf-writeups'
languageCode = 'en-us'
title = 'Writeups'

theme = "terminal"

[params]
  themeColor = "pink"

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Writeups"
    subtitle = "My CTF writeups for reference and studying"

  [languages.en.params.logo]
    logoText = "Writeups"
    logoHomeLink = "/"