baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Writeups'

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v3"

[params]
  themeColor = "pink"

[markup.goldmark.renderer]
  unsafe = true


[languages]
  [languages.en]
    languageName = "English"
    title = "Writeups"
    subtitle = "My CTF writeups for reference and studying"

  [languages.en.params.logo]
    logoText = "Writeups"
    logoHomeLink = "/"